#!/usr/bin/env bash
# 3. Redirection
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "s/server {/server {\n\terror-page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t}" /etc/nginx/sites-available/default
systemctl reload nginx
