#!/usr/bin/env bash
# 0. Double the number of webservers
apt-get update -y
apt-get install nginx -y
sed -i '/^\slocation.*/i \tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sed -i '/^\slocation.*/a \t\trewrite redirect_me https://google.com permanent;' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
systemctl restart nginx
