#!/usr/bin/env bash
# 0. Double the number of webservers
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed -i 's/^\slocations.*/i\tadd_header X-Served-By $hostname;/' /etc/nginx/sites-available/default
sudo systemctl restart nginx
