#!/usr/bin/env bash
# 1. Install your load balancer
sudo apt-get update -y
sudo apt-get install haproxy -y
file="/etc/haproxy/haproxy.cfg"
sudo echo -e "frontend my_frontend" >> "$file"
sudo echo -e "\tbind *:80" >> "$file"
sudo echo -e "\tdefault_backend my_backend" >> "$file"
sudo echo -e "backend my_backend" >> "$file"
sudo echo -e "\tbalance roundrobin" >> "$file"
sudo echo -e "\tserver web-01 100.25.152.12:80 check" >> "$file"
sudo echo -e "\tserver web-02 54.167.85.211:80 check" >> "$file"
sudo systemctl restart haproxy
