#!/usr/bin/env bash
# 1. Run Nginx as Nginx
sed -i 's/.*user .+;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx reload
