#!/usr/bin/env bash
# 1. Run Nginx as Nginx
config=$(cat /etc/nginx/nginx.conf)
cat <(echo "user nginx;") <(echo "$config") > /etc/nginx/nginx.conf
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
